# Generated by Django 3.0.2 on 2021-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('b', 'backlog'), ('p', 'in progress'), ('d', 'done')], default='b', max_length=1),
        ),
    ]
