# Generated by Django 3.0.2 on 2021-01-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0002_auto_20210118_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
