# Generated by Django 3.0.2 on 2021-01-18 09:50

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0003_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('b', 'backlog'), ('p', 'in progress'), ('d', 'done')], default='b', max_length=1),
        ),
    ]

    AddDefaultValue(
        model_name='task',
        name='status',
        value='b'
    )