# Generated by Django 3.0.2 on 2020-09-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0005_auto_20200311_0807'),
        ('toDoList', '0003_auto_20200319_0640'),
    ]

    operations = [
    ]
